config/routes.rb
Rails.application.routes.draw do
  namespace 'admin' do
    resources :proposals

    root 'proposals#index'
  end

  namespace 'voting' do
    resources :proposals, only: [:index, :show, :update] do
      collection do
        get 'summarize'
      end
    end

    root 'proposals#index'
  end

  namespace 'monitoring' do
    resources :proposals, only: [:index, :show] do
      collection do
        get 'summarize'
      end
      resources :comments, only: [:create]
    end

    root 'proposals#index'
  end

  resources :voters, only: [:new, :create, :update] do
    collection do
      get 'verification', to: 'voters#verify', as: :verify
      get 'signout'
    end
  end

  get '/terms-of-service', to: 'pages#terms_of_service'
  get '/privacy-policy',   to: 'pages#privacy_policy'

  root 'pages#home'
end

app/models/voter.rb
class Voter < ApplicationRecord
  has_and_belongs_to_many :proposals

  validates :email, format: /@/

  def verify!
    self.verified = true
    self.verification_token = nil
    self.save!
  end

  def generate_verification_token!
    self.verification_token = secure_token.to_i(16).to_s(36)
    self.save!
    self.verification_token
  end

  def voted?(proposal)
    return false unless proposal
    proposals.include?(proposal)
  end

  def to_s
    name || email
  end
end

app/controllers/voters_controller.rb
class VotersController < ApplicationController
  def new
    update_current_redirect_with(params[:redirect]) if params[:redirect]
    @voter = Voter.new
  end

  def create
    email = voter_params[:email]
    secret = voter_secret_params[:secret_data].to_h
    if RegisterVoter.call(email,secret)
      session[:verification_pending] = true
      redirect_to current_redirect!, notice: _("We've sent you a <strong>verification token</strong>, please see your inbox for further instructions.")
    else
      redirect_to new_voter_path, error: _('Something went wrong with the registration process. Please, <strong>try again</strong>.')
    end
  end

  def update
    @voter = Voter.find(params[:id])
    @voter.name = params[:voter][:name] if params[:voter] && !params[:voter][:name].blank?
    verify!
  end

  def verify
    @voter = Voter.find_by(verification_token: params[:token])
    if !@voter
      redirect_to new_voter_path, error: _('Something went wrong with the verification process. Please, <strong>try again</strong>.')
    elsif !@voter.verified? || !@voter.name
      render :verify
    else
      verify!
    end
  end

  def signout
    sign_out
    redirect_to root_path, success: _('<strong>Successfully signed out</strong>, sign in again to review your votes.')
  end

  private

  def verify!
    @voter.verify!
    session.delete(:verification_pending)
    sign_in(@voter)
    redirect_to current_redirect!, success: _('<strong>Successfully verified</strong>, you can now take part in the participatory budgeting process.')
  end

  def voter_params
    params.require(:voter).permit(:email)
  end

  def voter_secret_params
    return ActionController::Parameters.new({}) unless (params[:voter] && params[:voter][:secret_data])
    params.require(:voter).permit(secret_data: params[:voter][:secret_data].try(:keys))
  end
end

app/helpers/voters_helper.rb
module VotersHelper
end

app/views/voters/new.html.haml
= render 'partials/page-title', title: _('Sign in / Register')

.voters-new.container
  .row
    .col-lg-8.offset-lg-2
      .card
        .card-block
          = form_for @voter, as: :voter, url: voters_path, method: :post, class: 'voters-new' do |f|
            .form-group
              = f.label _('Email address')
              = f.text_field :email, class: 'form-control'
              = f.fields_for :secret_data do |df|
                - VoterSecret.list_of_secrets.each do |secret|
                  .form-group
                  = df.label secret, _(secret.humanize)
                  = df.text_field secret.to_sym, class: 'form-control'
            = f.submit _('Email me a link to sign in'), class: 'btn btn-primary'
        .card-block
          = render 'partials/data-protection'

app/views/voters/verify.html.haml
= render 'partials/page-title', title: _('Please provide your name')

.voters-new.container
  .row
    .col-lg-8.offset-lg-2
      .card
        .card-block
          = form_for @voter, as: :voter, url: voter_path(@voter), method: :patch, class: 'voters-new' do |f|
            .form-group
              = f.label _('Name')
              = f.text_field :name, class: 'form-control'
            = f.submit _('Continue'), class: 'btn btn-primary'
        .card-block
          = render 'partials/data-protection'